<?xml version="1.0" encoding="utf-8"?>
<!-- Created by Leo: http://leoeditor.com/leo_toc.html -->
<leo_file xmlns:leo="http://leoeditor.com/namespaces/leo-python-editor/1.1" >
<leo_header file_format="2"/>
<globals/>
<preferences/>
<find_panel_settings/>
<vnodes>
<v t="metaperl.20191124091501.2"><vh>Terrence-Monroe: Brannon</vh>
<v t="metaperl.20191124100336.1"><vh>Life Mission and Vision</vh>
<v t="metaperl.20191124100629.1"><vh>The Quiet.Center	</vh></v>
<v t="metaperl.20191124101243.1"><vh>IRS Slam Dunk</vh></v>
</v>
<v t="metaperl.20191124092807.1"><vh>Earthly Concerns</vh>
<v t="metaperl.20191124093745.1"><vh>Communication and Relationships</vh></v>
<v t="metaperl.20191124093656.1"><vh>Conspiracy Theory</vh></v>
<v t="metaperl.20191124093052.1"><vh>Social Media Links</vh></v>
<v t="metaperl.20191124093245.1"><vh>Streetdance</vh></v>
</v>
<v t="metaperl.20191124092401.1"><vh>Spirituality</vh>
<v t="metaperl.20191124092641.1"><vh>Sacred Sexuality</vh></v>
</v>
<v t="metaperl.20191124091553.1"><vh>Money, Tax and Law</vh>
<v t="metaperl.20191124091639.1"><vh>Have you Met Your Strawman?</vh></v>
<v t="metaperl.20191124091655.1"><vh>Have you fallen for the Income Tax Mass Hypnosis?</vh></v>
<v t="metaperl.20191124092010.1"><vh>Gold is Real Money but Crypto Rocks</vh></v>
</v>
</v>
</vnodes>
<tnodes>
<t tx="metaperl.20191124091501.2"></t>
<t tx="metaperl.20191124091553.1">Jack Slevkoff has a great website that shows how I think about money, tax and law - http://www.usavsus.info/

</t>
<t tx="metaperl.20191124091639.1">Do you know the difference between Terrence-Monroe: Brannon and TERRENCE MONROE BRANNON? If not, you have not met your strawman.

Your strawman was born the same day you were, but the government did not tell you about it - https://www.youtube.com/watch?v=ME7K6P7hlko&amp;feature=emb_title
</t>
<t tx="metaperl.20191124091655.1">If so, then you must read my article:
http://mymoneymagick.com/tax/do-not-file-or-pay-income-tax/
</t>
<t tx="metaperl.20191124092010.1">Gold is the longest, strongest store of value on Planet Earth:
http://static.livingcosmos.org/www.financial-freedom-club.com/Karatbars-A-to-Z.html

But crypto gives fast high-yield gains. How to marry them? Read my blog to see:
http://mymoneymagick.com/gold/what-cryptocurrency-is-backed-by-gold-kbc-coin-is/


</t>
<t tx="metaperl.20191124092401.1">View my spiritual resume for all the details:
https://docs.google.com/spreadsheets/d/1fK1Xj4BbusslkcFqq3I7b-mD7A195gbisdO8Af0xKbk/edit?usp=sharing</t>
<t tx="metaperl.20191124092641.1">the ancient Indians and Asians have a number of Daoist/Tantric practices. I've experimented with them. I currently find Orgasmic Mindfulness or the Teachings of Erwan Davon to be the most practical. Although I do miss female sacred spot massage - my what a bath of shakti that was.... read more at my blog - http://orgasmic-mindfulness.livingcosmos.org/

The divorce rate is over 50% and many of those in marriages are unhappy. www.unfencedrelationships.com provides a real relationship solution. JJ Roberts is a genius. Too bad he cares more about money for himself than forming a community.
</t>
<t tx="metaperl.20191124092807.1">
vegan/vegetarian with a host of experimentation detailed at https://docs.google.com/spreadsheets/d/1fK1Xj4BbusslkcFqq3I7b-mD7A195gbisdO8Af0xKbk/edit?usp=sharing</t>
<t tx="metaperl.20191124093052.1">* https://www.linkedin.com/in/softwareartisan
* http://facebook.com/terrence.brannon
* https://www.youtube.com/user/TheQuietCenter/playlists?view_as=subscriber
</t>
<t tx="metaperl.20191124093245.1">Love it - I moderate this  https://www.reddit.com/r/streetdance/
</t>
<t tx="metaperl.20191124093656.1">Maya does a wonderful dance of illusion:

* No planes flew into the World Trade Center on 9/11/2001.
* We do not living on a spinning, whirling ball. The earth is flat, level and still.

</t>
<t tx="metaperl.20191124093745.1">Non-violent communication is a powerful way to state your truth without giving away your power.

JJ Robert's book "Sex 3.0" changed the way I think about relationships. My endeavors in sacred sexuality are also down this line.
</t>
<t tx="metaperl.20191124100336.1">My life mission consists of inner work and outer work. The inner work is more important.
</t>
<t tx="metaperl.20191124100629.1">@language md @nocompile

What is the Quiet Center?
* a book written by John C. Lilly, inventor of the Isolation Tank
* the part of every hurricane: no matter how much craziness is occurring, every hurricane has a Quiet Center that a plane can fly into unperturbed.
* an analogy for the shakshibhava - the silent witness of all events. I AM = Sat-Chit-Ananda: the uncreated witness of the 5 lower sheaths: (1) food-sheath (2) prana sheath (3) lower-mind (4) higher-mind (5) bliss
* An intentional community based around spiritual practices that work certainly and work fast (15 minutes to 21 days). I spent 31 days at Madre Grande monastery and I did have a transformation but it could have been faster and more certain with the methods available at http://TheQuietCenter.org - orgasmic mindfulness, isolation tank, pranayama ... conflict resolution and forgiveness are a must in community ... who is really willing to sacrifice their ego in community?
</t>
<t tx="metaperl.20191124101243.1">Create the "IRS Slam Dunk" affidavit to free people from the lies and tricks of the IRS - how can anyone report income when the term is not defined in their 3 million word document?
</t>
</tnodes>
</leo_file>
